# Generated by Django 3.2.7 on 2021-09-09 23:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=31, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')])),
                ('tel_number_1', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')])),
                ('tel_number_2', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_company_deadline', models.DateField(blank=True, null=True)),
                ('customer_deadline', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('working_period', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('supply', models.BooleanField(blank=True, default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('excel_path', models.FilePathField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='office.customer')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='office.material')),
            ],
        ),
    ]
