# Generated by Django 3.2.7 on 2022-01-16 05:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20210911_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 1, 16), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='office.customer', verbose_name='顧客先'),
        ),
        migrations.AlterField(
            model_name='post',
            name='customer_deadline',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 16), null=True, verbose_name='客先納期'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excel_path',
            field=models.FilePathField(null=True, path=pathlib.PureWindowsPath('C:/Users/habir/OneDrive/デスクトップ/printer/office-master/data/excel')),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='図面'),
        ),
        migrations.AlterField(
            model_name='post',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='office.material', verbose_name='材料'),
        ),
        migrations.AlterField(
            model_name='post',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='my_company_deadline',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 16), null=True, verbose_name='社内納期'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='値段'),
        ),
        migrations.AlterField(
            model_name='post',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='図面の枚数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='supply',
            field=models.BooleanField(blank=True, default=False, verbose_name='支給されるならチェック'),
        ),
        migrations.AlterField(
            model_name='post',
            name='working_period',
            field=models.FloatField(blank=True, null=True, verbose_name='実働期間'),
        ),
        migrations.CreateModel(
            name='KidPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirial_number', models.IntegerField(blank=True, null=True, verbose_name='整理番号')),
                ('add_memo', models.TextField(blank=True, null=True, verbose_name='追加メモ')),
                ('material_name', models.TextField(blank=True, null=True, verbose_name='材質名')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.date(2022, 1, 16), null=True)),
                ('supply', models.BooleanField(blank=True, default=False, verbose_name='支給されるならチェック')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='個数')),
                ('my_company_deadline', models.DateField(blank=True, default=datetime.date(2022, 1, 16), null=True, verbose_name='社内納期')),
                ('customer_deadline', models.DateField(blank=True, default=datetime.date(2022, 1, 16), null=True, verbose_name='客先納期')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='値段')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='図面')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='office.customer', verbose_name='顧客先')),
                ('post_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='office.post', verbose_name='親情報')),
            ],
        ),
    ]
