# Generated by Django 4.1.7 on 2023-05-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0004_post_customer_done_post_my_company_done_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KidPost",
        ),
    ]
